config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :bookings
  resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users
  resources :sessions

  # jjj
  get 'about', to: 'about#index'
  get 'contact', to: 'contact#contact'

  # Defines the root path route ("/")
  root "about#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!

  include Pundit
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    #@customer = "ERIC"
    @bookings = Booking.all
   # @customers = Customer.all
  
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end


  # GET /bookings/new
  def new
    @booking = Booking.new
    @room = Room.all
   # @room_options = Room.all.map{ |u| [ u.roomNumber, u.name ] }
    @@customer = request.params["_id"]
    @name = Customer.where(id: @@customer).pluck(:firstName, :lastName).map { |x| x.flatten.join(' ') }
    @b = @name.shift.strip
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    
    @booking = Booking.new(booking_params)
    @booking.customer_id = @@customer
    #@booking.save


    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy
    
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:room_id, :start_date, :end_date, :issued_by, :booking_status, :closed_date, :closed_by, :comments)
      
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact
 end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:firstName, :lastName, :dateofBirth, :address, :email, :mobileNumber, :idType, :idNumber, :registeredBy, :comments)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  @users = User.order(created_at: desc)
  def about
    authorize @users
    

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

 
   

   

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>Room:</strong>
    <%= booking.room_id %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= booking.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= booking.end_date %>
  </p>

  <p>
    <strong>Issued by:</strong>
    <%= booking.issued_by %>
  </p>

  <p>
    <strong>Booking status:</strong>
    <%= booking.booking_status %>
  </p>

  <p>
    <strong>Closed date:</strong>
    <%= booking.closed_date %>
  </p>

  <p>
    <strong>Closed by:</strong>
    <%= booking.closed_by %>
  </p>

  <p>
    <strong>Comments:</strong>
    <%= booking.comments %>
  </p>

</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>




    <div class="card" style="width: 100%;" >
     <div class="card-header" style="background-color: #e3f2fd;">New Booking</div>
      <div class="card-body">

  
<div class="mb-3">
    <%= form.label :customer_name, "Client Name", style: "display: horizontal" %>
    <%= form.text_field :customer_name, class: "form-control", placeholder:  @b, disabled:true %>
  </div>

  <%
=begin%>
 <div class="mb-3">
    <%= form.label :customer_id, style: "display: horizontal" %>
    <%= form.number_field :customer_id, class: "form-control" %>
  </div> 
<%
=end%>

<%
=begin%>
   <div class="mb-3">
  <%= form.label :room_id, "Room Number", style: "display: block"%>
  <%= select_tag(:room_id, options_for_select(@room_options), class: "form-control" )%>
  </div> 
<%
=end%>

   <div class="mb-3">
  <%= form.label :room_id, "Room Number", style: "display: block"%>
    <%= form.select :room_id, @room.map { |t| [t.roomNumber, t.roomRate]}, {},id: "roomrates", class: "form-control", required: true  %>
  </div>

<%
=begin%>
   <div class="mb-3">
    <%= form.label :room_id, "Room Number", style: "display: horizontal" %>
    <%= form.number_field :room_id, class: "form-control", required: true %>
  </div> 
<%
=end%>

  <div class="mb-3">
    <%= form.label :start_date, "Check-in Date", style: "display: horizontal" %>
    <%= form.date_field :start_date, class: "form-control",id: "in_date",  required: true  %>
  </div>

  <div class="mb-3">
    <%= form.label :end_date,  "Check-out Date",style: "display: block" %>
    <%= form.date_field :end_date, class: "form-control",id: "out_date", required: true, :onchange => "getFormvalue()" %>
  </div>


<script type="text/javascript">
  function getFormvalue()
{
  
  const startDate  = $("#in_date").val();
  const endDate    = $("#out_date").val();

const diffInMs   = new Date(endDate) - new Date(startDate)
const diffInDays = diffInMs / (1000 * 60 * 60 * 24);
document.getElementById("bill").innerHTML = diffInDays;
document.getElementById("roomrate").innerHTML =  $("#roomrates").val() * diffInDays;


   //document.getElementById("bill").innerHTML = $("#roomrate").val();
}
</script>

 <%
=begin%>
 <div class="mb-3">
    <%= form.label :issued_by, style: "display: block" %>
    <%= form.number_field :issued_by, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :booking_status, style: "display: block" %>
    <%= form.number_field :booking_status, class: "form-control" %>
  </div>

 <div class="mb-3">
    <%= form.label :closed_date, style: "display: block" %>
    <%= form.date_field :closed_date, class: "form-control" %>
  </div>

 <div class="mb-3">
    <%= form.label :closed_by, style: "display: block" %>
    <%= form.number_field :closed_by, class: "form-control" %>
  </div>
 
<%
=end%>
 <div class="mb-3">
    <%= form.label :comments, style: "display: block" %>
    <%= form.text_area :comments, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Submit", class: "btn btn-primary"%>
  </div>

</div>

</div>
</div>

 <div class="col-sm-3">
  <div class="card">

   
     <div class="card-header" style="background-color: #e3f2fd;"><img src="" class="card-img-top" alt="..."> Cart</div>
      <div class="card-body">
      
       No of Nights<p class="badge bg-primary text-wrap" style="width: 6rem;" id="bill"></p>
       <br/>
       Room Rate<p class="fw-bold" id="roomrates"></p>
       <br/>
       Total Bill<p class="fw-bold" id="roomrate"></p>
           
      </div>
      </div>
      </div>
     
    </div>


<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Show this booking", @booking %> |
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bookings</h1>

<div id="bookings">
Hello <%= @customer %>
  <% @bookings.each do |booking| %>
    <%= render booking %>
    <p>
      <%= link_to "Show this booking", booking %>
    </p>
  <% end %>
</div>

<%= link_to "New booking", new_booking_path %>

app/views/bookings/new.html.erb
<br>
<br>
<br>

<div class="row">
    <div class="col-sm-3">
        
               <div class="list-group">
  <a href="#" class="list-group-item list-group-item-info list-group-item-action flex-column align-items-start active">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">List group item heading</h5>
      <br>
Hello <%= @b %>
      <small>3 days ago</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small>Donec id elit non mi porta.</small>
  </a>
  <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">List group item heading</h5>
      <small class="text-muted">3 days ago</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small class="text-muted">Donec id elit non mi porta.</small>
  </a>
  <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">List group item heading</h5>
      <small class="text-muted">3 days ago</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small class="text-muted">Donec id elit non mi porta.</small>
  </a>
</div>


          
    </div>
    <div class="col-sm-6">
       
               <%= render "form", booking: @booking %>


           
    </div>

        <div class="col-sm-3">
       
              Hello <%= @customer %>
           
    </div>
    
    
</div>



<br>
Hello <%= @customer %>

<div>
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @booking %>

<div>
  <%= link_to "Edit this booking", edit_booking_path(@booking) %> |
  <%= link_to "Back to bookings", bookings_path %>

  <%= button_to "Destroy this booking", @booking, method: :delete %>
</div>

app/views/contact/contact.html.erb
<h1>Hello contact</h1>

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <p>
    <strong>Firstname:</strong>
    <%= customer.firstName %>
  </p>

  <p>
    <strong>Lastname:</strong>
    <%= customer.lastName %>
  </p>

  <p>
    <strong>Dateofbirth:</strong>
    <%= customer.dateofBirth %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= customer.address %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= customer.email %>
  </p>

  <p>
    <strong>Mobilenumber:</strong>
    <%= customer.mobileNumber %>
  </p>

  <p>
    <strong>Idtype:</strong>
    <%= customer.idType %>
  </p>

  <p>
    <strong>Idnumber:</strong>
    <%= customer.idNumber %>
  </p>

  <p>
    <strong>Registeredby:</strong>
    <%= customer.registeredBy %>
  </p>

  <p>
    <strong>Comments:</strong>
    <%= customer.comments %>
  </p>

</div>

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

      <div class="card" style="width: 100%;" >
     <div class="card-header" style="background-color: #e3f2fd;">New Customer</div>
      <div class="card-body">

  <div class="mb-3">
    <%= form.label :firstName, style: "display: block" %>
    <%= form.text_field :firstName, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :lastName, style: "display: block" %>
    <%= form.text_field :lastName, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :dateofBirth, style: "display: block" %>
    <%= form.date_field :dateofBirth, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :mobileNumber, style: "display: block" %>
    <%= form.text_field :mobileNumber, class: "form-control" %>
  </div class="mb-3">

  <div class="mb-3">
    <%= form.label :idType, style: "display: block" %>
    <%= form.text_field :idType, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :idNumber, style: "display: block" %>
    <%= form.text_field :idNumber, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :registeredBy, style: "display: block" %>
    <%= form.number_field :registeredBy, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :comments, "Comment", style: "display: block" %>
    <%= form.text_field :comments, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
  </div>
  </div>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Show this customer", @customer %> |
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/index.html.erb
<style>
  .table-hover tbody tr:hover td {
    background: #e3f2fd;
  }
</style>





<div class="container">
  <div class="page-header">
  <br/><br/><br/>
    
    <h4><span class="label label-primary">Customer Information</span></h4>
  </div>
</div>
<br/>



<div class="container">
<input class="form-control" id="myFilter" type="text" placeholder="Search here">

  <br>
  
  <table class="table table-striped table-hover">
    <thead class="table-primary">
      <tr>
        <th>Name</th>
        <th>Pone Number</th>
        
        <th>Actions</th>
        <th>Actions</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody  id="productTable", class="table-group-divider">
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.firstName + " " + customer.lastName %></td>
          <td><%= customer.mobileNumber %></td>
          <td><%= link_to "Book a Room", new_booking_path(:_id => customer.id) %></td>

            <td >
            <%= link_to "Show", customer_path(customer), class: 'label label-info'%>
            <%= link_to "Edit", edit_customer_path(customer), class: 'label label-success'%>
            
            <%= link_to "Delete", @customer, method: :destroy, data: { confirm: "Are you sure?" }, class: 'label label-danger' %>
          </td>
          <td> --- </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <script>
$(document).ready(function(){
  $("#myFilter").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#productTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
</div>

app/views/customers/new.html.erb
<br>
<br>
<br>

<div class="row">
    <div class="col-sm-3">
        
               <div class="list-group">
  <a href="#" class="list-group-item list-group-item-info list-group-item-action flex-column align-items-start active">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">List group item heading</h5>
      <small>3 days ago</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small>Donec id elit non mi porta.</small>
  </a>
  <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">List group item heading</h5>
      <small class="text-muted">3 days ago</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small class="text-muted">Donec id elit non mi porta.</small>
  </a>
  <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">List group item heading</h5>
      <small class="text-muted">3 days ago</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small class="text-muted">Donec id elit non mi porta.</small>
  </a>
</div>
          
    </div>
    <div class="col-sm-7">
       
              <%= render "form", customer: @customer %>
           
    </div>
</div>




<br>



<br>

<div>
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @customer %>

<div>
  <%= link_to "Edit this customer", edit_customer_path(@customer) %> |
  <%= link_to "Back to customers", customers_path %>

  <%= button_to "Destroy this customer", @customer, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!--
    Bootstrap code
    -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">	
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

  </head>

  <body>
  
<nav class="navbar fixed-top navbar-expand-lg" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
	  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
          
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
  <div class = "container">
 
    <%= yield %>
	</div>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p>
    <strong>Name:</strong>
    <%= room.name %>
  </p>

</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<style>
  .table-hover tbody tr:hover td {
    background: #e3f2fd;
  }
</style>

<div class="container">
  <div class="page-header">
  <br/><br/><br/>
    <h1>Blog</h1>
    <h4><span class="label label-primary">This is my first blog application with Bootstrap and Rails :D </span></h4>
  </div>
</div>
<br/>
<div class="container">
  <table class="table table-striped table-hover">
    <thead class="table-primary">
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Actions</th>
        <th>Actions</th>
        <th>Actions</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      <% @rooms.each do |room| %>
        <tr>
          <td><%= room.name %></td>
          <td><%= room.id %></td>
          <td><%= room.id %></td>
          <td><%= link_to "Book a Room", new_booking_path(:_id => room.id) %></td>

            <td class="text-center">
            <%= link_to "Show", room_path(room), class: 'label label-info'%>
            <%= link_to "Edit", edit_room_path(room), class: 'label label-success'%>
            
            <%= link_to "Delete", @room, method: :destroy, data: { confirm: "Are you sure?" }, class: 'label label-danger' %>
          </td>
          <td> --- </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to "Edit this room", edit_room_path(@room) %> |
  <%= link_to "Back to rooms", rooms_path %>

  <%= button_to "Destroy this room", @room, method: :delete %>
</div>